name: cyberneom
description: Guided meditation with your own voice
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.0+18

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  neom_commons:
    git:
      url: git@github.com:Cyberneom/neom_commons.git
  neom_events:
    git:
      url: git@github.com:Cyberneom/neom_events.git
  neom_frequencies:
    git:
      url: https://github.com/Cyberneom/neom_frequencies.git
  neom_generator:
    git:
      url: https://github.com/Cyberneom/neom_generator.git
  neom_home:
    git:
      url: git@github.com:Cyberneom/neom_home.git
  neom_timeline:
    git:
      url: git@github.com:Cyberneom/neom_timeline.git
  neom_posts:
    git:
      url: git@github.com:Cyberneom/neom_posts.git
  neom_profile:
    git:
      url: git@github.com:Cyberneom/neom_profile.git
  neom_bands:
    git:
      url: git@github.com:emmanuel-montoya/neom_bands.git
  neom_instruments:
    git:
      url: git@github.com:Cyberneom/neom_instruments.git
  neom_itemlists:
    git:
      url: git@github.com:Cyberneom/neom_itemlists.git
  neom_inbox:
    git:
      url: git@github.com:Cyberneom/neom_inbox.git
  neom_onboarding:
    git:
      url: git@github.com:Cyberneom/neom_onboarding.git
  neom_admin:
    git:
      url: git@github.com:Cyberneom/neom_admin.git
  neom_requests:
    git:
      url: git@github.com:Cyberneom/neom_requests.git
  neom_notifications:
    git:
      url: git@github.com:Cyberneom/neom_notifications.git
  neom_calendar:
    git:
      url: git@github.com:Cyberneom/neom_calendar.git
  neom_jobs:
    git:
      url: git@github.com:emmanuel-montoya/neom_jobs.git
  neom_booking:
    git:
      url: git@github.com:emmanuel-montoya/neom_booking.git
  neom_commerce:
    git:
      url: git@github.com:emmanuel-montoya/neom_commerce.git
  neom_audio_player:
    git:
      url: https://github.com/Cyberneom/neom_audio_player.git
  flutter_launcher_icons: ^0.13.1
  surround_frequency_generator: ^1.0.0

  #USED FOR NeomMusicWidget.kt
  home_widget: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.1.11
  dependency_validator: ^3.2.0

flutter_test:
  sdk: flutter

flutter_icons:
  image_path: assets/appIcon.png
  android: true
  ios: true
  adaptive_icon_foreground: "assets/appIcon.png"

flutter:
  uses-material-design: true

  fonts:
    - family: Open-Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800

  assets:
    - assets/
    - assets/elements/
    - assets/fonts/
    - assets/images/
    - assets/images/directory/
    - assets/images/events/
    - assets/images/rating/
    - assets/images/release_upload/
    - assets/images/music_player/
    - assets/images/music_player/xtras/
    - assets/logos/
    - assets/logos/third-party/
    - assets/sounds/
    - assets/event_activities/
    - assets/properties.json
    - assets/frequencies.json
