// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// Generated file. Do not edit.
//

import PackageDescription

let package = Package(
    name: "FlutterGeneratedPluginSwiftPackage",
    platforms: [
        .iOS("13.0")
    ],
    products: [
        .library(name: "FlutterGeneratedPluginSwiftPackage", type: .static, targets: ["FlutterGeneratedPluginSwiftPackage"])
    ],
    dependencies: [
        .package(name: "app_links", path: "../.packages/app_links-7.0.0"),
        .package(name: "arkit_plugin", path: "../.packages/arkit_plugin-1.4.0"),
        .package(name: "audio_service", path: "../.packages/audio_service-0.18.19"),
        .package(name: "audio_session", path: "../.packages/audio_session-0.2.4"),
        .package(name: "awesome_notifications", path: "../.packages/awesome_notifications-0.12.1"),
        .package(name: "camera_avfoundation", path: "../.packages/camera_avfoundation-0.10.2"),
        .package(name: "cloud_firestore", path: "../.packages/cloud_firestore-6.7.1"),
        .package(name: "cloud_functions", path: "../.packages/cloud_functions-6.3.5"),
        .package(name: "connectivity_plus", path: "../.packages/connectivity_plus-7.3.0"),
        .package(name: "easy_video_editor", path: "../.packages/easy_video_editor-0.1.6"),
        .package(name: "file_picker", path: "../.packages/file_picker-11.0.2"),
        .package(name: "firebase_ai", path: "../.packages/firebase_ai-3.14.1"),
        .package(name: "firebase_app_check", path: "../.packages/firebase_app_check-0.4.5+2"),
        .package(name: "firebase_auth", path: "../.packages/firebase_auth-6.5.6"),
        .package(name: "firebase_core", path: "../.packages/firebase_core-4.12.1"),
        .package(name: "firebase_crashlytics", path: "../.packages/firebase_crashlytics-5.2.6"),
        .package(name: "firebase_messaging", path: "../.packages/firebase_messaging-16.4.3"),
        .package(name: "firebase_storage", path: "../.packages/firebase_storage-13.4.5"),
        .package(name: "flutter_blue_plus_darwin", path: "../.packages/flutter_blue_plus_darwin-7.0.3"),
        .package(name: "flutter_image_compress_common", path: "../.packages/flutter_image_compress_common-1.1.1"),
        .package(name: "flutter_onnxruntime", path: "../.packages/flutter_onnxruntime-1.8.2"),
        .package(name: "flutter_pdfview", path: "../.packages/flutter_pdfview-1.4.4"),
        .package(name: "flutter_soloud", path: "../.packages/flutter_soloud-4.1.3"),
        .package(name: "geocoding_darwin", path: "../.packages/geocoding_darwin-1.0.2"),
        .package(name: "geolocator_apple", path: "../.packages/geolocator_apple-2.3.14"),
        .package(name: "google_sign_in_ios", path: "../.packages/google_sign_in_ios-6.3.0"),
        .package(name: "image_cropper", path: "../.packages/image_cropper-12.2.1"),
        .package(name: "image_picker_ios", path: "../.packages/image_picker_ios-0.8.13+6"),
        .package(name: "in_app_purchase_storekit", path: "../.packages/in_app_purchase_storekit-0.4.10+1"),
        .package(name: "just_audio", path: "../.packages/just_audio-0.10.6"),
        .package(name: "mobile_scanner", path: "../.packages/mobile_scanner-7.4.0"),
        .package(name: "package_info_plus", path: "../.packages/package_info_plus-9.0.1"),
        .package(name: "permission_handler_apple", path: "../.packages/permission_handler_apple-9.4.10"),
        .package(name: "photo_manager", path: "../.packages/photo_manager-3.10.0"),
        .package(name: "pointer_interceptor_ios", path: "../.packages/pointer_interceptor_ios-0.10.1+1"),
        .package(name: "pro_image_editor", path: "../.packages/pro_image_editor-13.2.3"),
        .package(name: "pro_video_editor", path: "../.packages/pro_video_editor-1.22.0"),
        .package(name: "record_ios", path: "../.packages/record_ios-2.1.1"),
        .package(name: "sensors_plus", path: "../.packages/sensors_plus-7.1.0"),
        .package(name: "share_plus", path: "../.packages/share_plus-12.0.2"),
        .package(name: "shared_preferences_foundation", path: "../.packages/shared_preferences_foundation-2.5.6"),
        .package(name: "sign_in_with_apple", path: "../.packages/sign_in_with_apple-8.1.0"),
        .package(name: "sqflite_darwin", path: "../.packages/sqflite_darwin-2.4.2"),
        .package(name: "stripe_ios", path: "../.packages/stripe_ios-13.1.0"),
        .package(name: "url_launcher_ios", path: "../.packages/url_launcher_ios-6.4.1"),
        .package(name: "video_player_avfoundation", path: "../.packages/video_player_avfoundation-2.11.0"),
        .package(name: "wakelock_plus", path: "../.packages/wakelock_plus-1.5.2"),
        .package(name: "webview_flutter_wkwebview", path: "../.packages/webview_flutter_wkwebview-3.25.1"),
        .package(name: "FlutterFramework", path: "../.packages/FlutterFramework")
    ],
    targets: [
        .target(
            name: "FlutterGeneratedPluginSwiftPackage",
            dependencies: [
                .product(name: "app-links", package: "app_links"),
                .product(name: "arkit-plugin", package: "arkit_plugin"),
                .product(name: "audio-service", package: "audio_service"),
                .product(name: "audio-session", package: "audio_session"),
                .product(name: "awesome-notifications", package: "awesome_notifications"),
                .product(name: "camera-avfoundation", package: "camera_avfoundation"),
                .product(name: "cloud-firestore", package: "cloud_firestore"),
                .product(name: "cloud-functions", package: "cloud_functions"),
                .product(name: "connectivity-plus", package: "connectivity_plus"),
                .product(name: "easy-video-editor", package: "easy_video_editor"),
                .product(name: "file-picker", package: "file_picker"),
                .product(name: "firebase-ai", package: "firebase_ai"),
                .product(name: "firebase-app-check", package: "firebase_app_check"),
                .product(name: "firebase-auth", package: "firebase_auth"),
                .product(name: "firebase-core", package: "firebase_core"),
                .product(name: "firebase-crashlytics", package: "firebase_crashlytics"),
                .product(name: "firebase-messaging", package: "firebase_messaging"),
                .product(name: "firebase-storage", package: "firebase_storage"),
                .product(name: "flutter-blue-plus-darwin", package: "flutter_blue_plus_darwin"),
                .product(name: "flutter-image-compress-common", package: "flutter_image_compress_common"),
                .product(name: "flutter-onnxruntime", package: "flutter_onnxruntime"),
                .product(name: "flutter-pdfview", package: "flutter_pdfview"),
                .product(name: "flutter-soloud", package: "flutter_soloud"),
                .product(name: "geocoding-darwin", package: "geocoding_darwin"),
                .product(name: "geolocator-apple", package: "geolocator_apple"),
                .product(name: "google-sign-in-ios", package: "google_sign_in_ios"),
                .product(name: "image-cropper", package: "image_cropper"),
                .product(name: "image-picker-ios", package: "image_picker_ios"),
                .product(name: "in-app-purchase-storekit", package: "in_app_purchase_storekit"),
                .product(name: "just-audio", package: "just_audio"),
                .product(name: "mobile-scanner", package: "mobile_scanner"),
                .product(name: "package-info-plus", package: "package_info_plus"),
                .product(name: "permission-handler-apple", package: "permission_handler_apple"),
                .product(name: "photo-manager", package: "photo_manager"),
                .product(name: "pointer-interceptor-ios", package: "pointer_interceptor_ios"),
                .product(name: "pro-image-editor", package: "pro_image_editor"),
                .product(name: "pro-video-editor", package: "pro_video_editor"),
                .product(name: "record-ios", package: "record_ios"),
                .product(name: "sensors-plus", package: "sensors_plus"),
                .product(name: "share-plus", package: "share_plus"),
                .product(name: "shared-preferences-foundation", package: "shared_preferences_foundation"),
                .product(name: "sign-in-with-apple", package: "sign_in_with_apple"),
                .product(name: "sqflite-darwin", package: "sqflite_darwin"),
                .product(name: "stripe-ios", package: "stripe_ios"),
                .product(name: "url-launcher-ios", package: "url_launcher_ios"),
                .product(name: "video-player-avfoundation", package: "video_player_avfoundation"),
                .product(name: "wakelock-plus", package: "wakelock_plus"),
                .product(name: "webview-flutter-wkwebview", package: "webview_flutter_wkwebview"),
                .product(name: "FlutterFramework", package: "FlutterFramework")
            ]
        )
    ]
)
