org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g -XX:-TieredCompilation -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.java.home=/opt/homebrew/opt/openjdk@21
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
kotlin.jvm.target.validation.mode=ignore
